[[task]]
id = 2
task_name = "add read feature"
completion = true

[[task]]
id = 3
task_name = "add modifying completion"
completion = true

[[task]]
id = 4
task_name = "add more readability"
completion = false

[[task]]
id = 5
task_name = "write man page (maybe"
completion = false

[[task]]
id = 6
task_name = "add better feedback to commands"
completion = false
